

export const RETRIEVE_PRODUCTS = "RETRIEVE_PRODUCTS";
export const PRODUCTS_RETRIEVED = "PROCUTS_RETRIEVED";

export const RETRIEVE_PRODUCT = "RETRIEVE_PRODUCT";
export const PRODUCT_RETRIEVED = "PRODUCT_RETRIEVED";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const PRODUCT_CREATED = "PRODUCT_CREATED";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const PRODUCT_UPDATED = "PRODUCT_UPDATED";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_DELETED = "PRODUCT_DELETED";