

export const RETRIEVE_PRODUCTS = "RETRIEVE_PRODUCTS";
export const PRODUCTS_RETRIEVED = "PROCUTS_RETRIEVED";

export const RETRIEVE_PRODUCT = "RETRIEVE_PRODUCT";
export const PRODUCT_RETRIEVED = "PRODUCT_RETRIEVED";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const PRODUCT_CREATED = "PRODUCT_CREATED";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const PRODUCT_UPDATED = "PRODUCT_UPDATED";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_DELETED = "PRODUCT_DELETED";

export const ADD_TOAST = "ADD_TOAST";
export const REMOVE_TOAST = "REMOVE_TOAST";

export const HYDRATE_MY_USER_FROM_LOGIN = "HYDRATE_MY_USER_FROM_LOGIN";
export const HYDRATE_MY_USER_FROM_VERIFY_CODE = "HYDRATE_MY_USER_FROM_VERIFY_CODE";
export const HYDRATE_MY_USER_FROM_GOOGLE = "HYDRATE_MY_USER_FROM_GOOGLE";
export const UPDATE_MY_USER = "UPDATE_MY_USER";

export const ADD_PRODUCT_IN_BASKET = "ADD_PRODUCT_IN_BASKET";
export const REMOVE_PRODUCT_FROM_BASKET = "REMOVE_PRODUCT_FROM_BASKET";
export const RETRIEVE_PRODUCTS_FROM_BASKET = "RETRIEVE_PRODUCTS_FROM_BASKET";

export const RETRIEVE_SPECIFIC_USER = "RETRIEVE_SPECIFIC_USER";
export const SPECIFIC_USER_RETRIEVED = "SPECIFIC_USER_RETRIEVED";

export const UPDATE_SPECIFIC_USER = "UPDATE_SPECIFIC_USER";
export const SPECIFIC_USER_UPDATED = "SPECIFIC_USER_UDPATED";

export const DELETE_SPECIFIC_USER = "DELETE_SPECIFIC_USER";
export const SPECIFIC_USER_DELETED = "SPECIFIC_USER_DELETED";

export const LOGOUT_USER = "LOGOUT_USER";

export const RETRIEVE_PARTNERS = "RETRIEVE_PARTNERS";
export const PARTNERS_RETRIEVED = "PARTNERS_RETRIEVED";

export const RETRIEVE_RESTAURANTS = "RETRIEVE_RESTAURANTS";
export const RESTAURANTS_RETRIEVED = "RESTAURANTS_RETRIEVED";

export const RETRIEVE_COMMANDS = "RETRIEVE_COMMANDS";
export const COMMANDS_RETRIEVED = "COMMANDS_RETRIEVED";

export const RETRIEVE_HISTO_BY_USER = "RETRIEVE_HISTO_BY_USER";
export const HISTO_BY_USER_RETRIEVED = "HISTO_BY_USER_RETRIEVED";

export const RETRIEVE_RESTAURANT = "RETRIEVE_RESTAURANT";
export const RESTAURANT_RETRIEVED = "RESTAURANT_RETRIEVED";

export const RETRIEVE_RESTAURANTS_BY_PARTNER = "RETRIEVE_RESTAURANTS_BY_PARTNER";
export const RESTAURANTS_BY_PARTNER_RETRIEVED = "RESTAURANTS_BY_PARTNER_RETRIEVED";

export const CREATE_RESTAURANT = "CREATE_RESTAURANT";
export const RESTAURANT_CREATED = "RESTAURANT_CREATED";

export const UPDATE_RESTAURANT = "UPDATE_RESTAURANT";
export const RESTAURANT_UPDATED = "RESTAURANT_UPDATED";

export const DELETE_RESTAURANT = "DELETE_RESTAURANT";
export const RESTAURANT_DELETED = "RESTAURANT_DELETED";

export const CREATE_CATEGORY= "CREATE_CATEGORY";
export const CATEGORY_CREATED = "CATEGORY_CREATED";

export const RETRIEVE_CATEGORIES = "RETRIEVE_CATEGORIES";
export const CATEGORIES_RETRIEVED = "CATEGORIES_RETRIEVED";

export const CREATE_COMMAND = "CREATE_COMMAND";
export const COMMAND_CREATED = "COMMAND_CREATED";
