

export const RETRIEVE_PRODUCTS = "RETRIEVE_PRODUCTS";
export const PRODUCTS_RETRIEVED = "PROCUTS_RETRIEVED";

export const RETRIEVE_PRODUCT = "RETRIEVE_PRODUCT";
export const PRODUCT_RETRIEVED = "PRODUCT_RETRIEVED";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const PRODUCT_CREATED = "PRODUCT_CREATED";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const PRODUCT_UPDATED = "PRODUCT_UPDATED";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_DELETED = "PRODUCT_DELETED";

export const ADD_TOAST = "ADD_TOAST";
export const REMOVE_TOAST = "REMOVE_TOAST";

export const HYDRATE_MY_USER_FROM_LOGIN = "HYDRATE_MY_USER_FROM_LOGIN";
export const HYDRATE_MY_USER_FROM_VERIFY_CODE = "HYDRATE_MY_USER_FROM_VERIFY_CODE";
export const HYDRATE_MY_USER_FROM_GOOGLE = "HYDRATE_MY_USER_FROM_GOOGLE";
export const UPDATE_MY_USER = "UPDATE_MY_USER";

export const ADD_PRODUCT_IN_BASKET = "ADD_PRODUCT_IN_BASKET";
export const REMOVE_PRODUCT_FROM_BASKET = "REMOVE_PRODUCT_FROM_BASKET";

export const RETRIEVE_SPECIFIC_USER = "RETRIEVE_SPECIFIC_USER";
export const SPECIFIC_USER_RETRIEVED = "SPECIFIC_USER_RETRIEVED";

export const UPDATE_SPECIFIC_USER = "UPDATE_SPECIFIC_USER";
export const SPECIFIC_USER_UPDATED = "SPECIFIC_USER_UDPATED";

export const RETRIEVE_PARTNERS = "RETRIEVE_PARTNERS";
export const PARTNERS_RETRIEVED = "PARTNERS_RETRIEVED";
